name: Lint Commit Messages

on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: git fetch --all

      - name: troubleshooting
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          git remote -v
          git branch -a
          echo "$GITHUB_CONTEXT"

      - run: npm ci --no-save
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run:
          npm run lint:commit -- --from="origin/${{ github.base_ref }}"
          --to="origin/${{github.head_ref }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
