name: Release

on:
  push:
    branches:
      - gpr

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: docker login
        run: echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: validate before release
        run: |
          printenv
          npm ci --no-save
          npm run lint
          npm run lint:md
          npm run test
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true

      - name: docker build
        run: docker build -t docker.pkg.github.com/codfish/actions-playground:latest .

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GPR Publish

      - name: docker push latest
        run: $DOCKER_URL/codfish/actions-playground:latest
        env:
          DOCKER_URL: docker.pkg.github.com

      - name: docker push versions
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          docker tag $DOCKER_URL/codfish/actions-playground $DOCKER_URL/codfish/actions-playground:$VERSION_TAG
          docker tag $DOCKER_URL/codfish/actions-playground $DOCKER_URL/codfish/actions-playground:$MAJOR_TAG
          docker push $DOCKER_URL/codfish/actions-playground:$VERSION_TAG
          docker push $DOCKER_URL/codfish/actions-playground:$MAJOR_TAG
        env:
          VERSION_TAG: v${{ steps.semantic.outputs.release-version }}
          MAJOR_TAG: v${{ steps.semantic.outputs.release-major }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com
